In [5]:
import yfinance as yf

# Microsoft (MSFT)에 대한 Ticker 객체 생성
msft = yf.Ticker("MSFT") # AMZN/META/

# Ticker 객체에 대한 정보 출력 (.py에서 실행할 때는 print(msft.info)로 사용)
display(msft.info)

{'address1': 'One Microsoft Way',
 'city': 'Redmond',
 'state': 'WA',
 'zip': '98052-6399',
 'country': 'United States',
 'phone': '425 882 8080',
 'website': 'https://www.microsoft.com',
 'industry': 'Software - Infrastructure',
 'industryKey': 'software-infrastructure',
 'industryDisp': 'Software - Infrastructure',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': "Microsoft Corporation, a technology company, develops and supports a portfolio of technology solutions for individuals and businesses worldwide. Its products include operating systems, server applications, business solution applications, software development tools, desktop and server management tools, and video games; and devices, such as PCs, tablets, gaming and entertainment consoles, other intelligent devices, and related accessories. The company's Productivity and Business Processes segment offers Microsoft 365 Commercial, Enterprise Mobility + Security, Power BI, Exchange, SharePoint, Microsoft Teams, Microsoft 365 Security and Compliance, Microsoft 365 Copilot, and Windows Commercial on-premises and Office licensed on-premises. This segment also provides Microsoft 365 Consumer products and cloud services; LinkedIn, including talent solutions, marketing solutions, subscriptions, and sales solutions; Dynamics 365, a set of cloud-based applications; and on-premises ERP and CRM applications. Its Intelligent Cloud segment offers server products and cloud services; cloud and AI consumption-based services, GitHub cloud services, health and life sciences cloud services, as well as virtual desktop offerings, and other cloud services; SQL Server, Windows Server, Visual Studio, System Center, and related client access licenses; and enterprise support services, industry solutions, Microsoft partner network, and learning experience. The company's More Personal Computing segment provides Windows OEM licensing and devices comprising Surface and PC accessories; XBOX hardware, and XBOX first- and third-party content and services; XBOX Game Pass and other subscriptions; XBOX Cloud Gaming, advertising, and other cloud services; and search advertising consisting of Bing, Copilot, Microsoft News, Microsoft Edge, and third-party affiliates. It sells its products through partners and retail networks. The company was founded in 1975 and is headquartered in Redmond, Washington.",
 'fullTimeEmployees': 223000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Satya  Nadella',
   'age': 58,
   'title': 'Chairman & CEO',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 12251294,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Bradford L. Smith LCA',
   'age': 66,
   'title': 'President & Vice Chairman',
   'yearBorn': 1959,
   'fiscalYear': 2025,
   'totalPay': 4532750,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Amy E. Hood',
   'age': 53,
   'title': 'Executive VP & CFO',
   'yearBorn': 1972,
   'fiscalYear': 2025,
   'totalPay': 4444191,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Takeshi  Numoto',
   'age': 54,
   'title': 'Executive VP & Chief Marketing Officer',
   'yearBorn': 1971,
   'fiscalYear': 2025,
   'totalPay': 2871250,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Judson B. Althoff',
   'age': 52,
   'title': 'Executive VP & CEO of Commercial Business',
   'yearBorn': 1973,
   'fiscalYear': 2025,
   'totalPay': 4490115,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Carolina  Dybeck Happe',
   'age': 53,
   'title': 'Executive VP & COO',
   'yearBorn': 1972,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Alice L. Jolla',
   'age': 59,
   'title': 'Corporate VP & Chief Accounting Officer',
   'yearBorn': 1966,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Matthew  Kerner',
   'title': 'CTO & Corporate VP of Worldwide Sales and Solutions',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Jonathan  Neilson',
   'title': 'Vice President of Investor Relations',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Jonathan M. Palmer',
   'title': 'Corporate Vice President & Chief Legal Officer',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 9,
 'boardRisk': 7,
 'compensationRisk': 5,
 'shareHolderRightsRisk': 2,
 'overallRisk': 5,
 'governanceEpochDate': 1785542400,
 'compensationAsOfEpochDate': 1767139200,
 'irWebsite': 'http://www.microsoft.com/investor/default.aspx',
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 480.35,
 'open': 481.54,
 'dayLow': 477.1505,
 'dayHigh': 484.27,
 'regularMarketPreviousClose': 480.35,
 'regularMarketOpen': 481.54,
 'regularMarketDayLow': 477.1505,
 'regularMarketDayHigh': 484.27,
 'dividendRate': 3.64,
 'dividendYield': 0.76,
 'exDividendDate': 1787184000,
 'payoutRatio': 0.1983,
 'fiveYearAvgDividendYield': 0.79,
 'beta': 1.099,
 'trailingPE': 26.801893,
 'forwardPE': 20.431183,
 'volume': 23714829,
 'regularMarketVolume': 23714829,
 'averageVolume': 40351725,
 'averageVolume10days': 30124170,
 'averageDailyVolume10Day': 30124170,
 'bid': 480.53,
 'ask': 481.63,
 'bidSize': 3,
 'askSize': 1,
 'marketCap': 3576365580288,
 'nonDilutedMarketCap': 3566860776601,
 'fiftyTwoWeekLow': 349.2,
 'fiftyTwoWeekHigh': 553.72,
 'allTimeHigh': 555.45,
 'allTimeLow': 0.088542,
 'priceToSalesTrailing12Months': 10.777411,
 'fiftyDayAverage': 413.8216,
 'twoHundredDayAverage': 432.1719,
 'trailingAnnualDividendRate': 3.64,
 'trailingAnnualDividendYield': 0.007577808,
 'currency': 'USD',
 'tradeable': False,
 'enterpriseValue': 3618830811136,
 'profitMargins': 0.40305,
 'floatShares': 7414481428,
 'sharesOutstanding': 7425545491,
 'sharesShort': 81311791,
 'sharesShortPriorMonth': 89063316,
 'sharesShortPreviousMonthDate': 1782777600,
 'dateShortInterest': 1785456000,
 'sharesPercentSharesOut': 0.011,
 'heldPercentInsiders': 0.00090000004,
 'heldPercentInstitutions': 0.75967,
 'shortRatio': 2.17,
 'shortPercentOfFloat': 0.011,
 'impliedSharesOutstanding': 7425545491,
 'bookValue': 59.565,
 'priceToBook': 8.085789,
 'lastFiscalYearEnd': 1782777600,
 'nextFiscalYearEnd': 1814313600,
 'mostRecentQuarter': 1782777600,
 'earningsQuarterlyGrowth': 0.313,
 'netIncomeToCommon': 133748998144,
 'trailingEps': 17.97,
 'forwardEps': 23.57328,
 'pegRatio': 1.61,
 'lastSplitFactor': '2:1',
 'lastSplitDate': 1045526400,
 'enterpriseToRevenue': 10.905,
 'enterpriseToEbitda': 18.631,
 '52WeekChange': -0.057712317,
 'SandP52WeekChange': 0.2080195,
 'lastDividendValue': 0.91,
 'lastDividendDate': 1779321600,
 'quoteType': 'EQUITY',
 'currentPrice': 481.63,
 'targetHighPrice': 870.0,
 'targetLowPrice': 400.0,
 'targetMeanPrice': 569.5583,
 'targetMedianPrice': 550.0,
 'recommendationMean': 1.35714,
 'recommendationKey': 'strong_buy',
 'numberOfAnalystOpinions': 53,
 'totalCash': 76842999808,
 'totalCashPerShare': 10.348,
 'ebitda': 194237005824,
 'totalDebt': 128812998656,
 'quickRatio': 1.099,
 'currentRatio': 1.23,
 'totalRevenue': 331839012864,
 'debtToEquity': 29.118,
 'revenuePerShare': 44.668,
 'returnOnAssets': 0.14088,
 'returnOnEquity': 0.34039003,
 'grossProfits': 225465008128,
 'freeCashflow': 16545500160,
 'operatingCashflow': 182934994944,
 'earningsGrowth': 0.317,
 'revenueGrowth': 0.177,
 'grossMargins': 0.67944,
 'ebitdaMargins': 0.58534,
 'operatingMargins': 0.45111,
 'financialCurrency': 'USD',
 'symbol': 'MSFT',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Nasdaq Real Time Price',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'corporateActions': [{'header': 'Dividend',
   'message': 'MSFT announced a cash dividend of $0.91 with an ex-date of Aug. 20, 2026',
   'meta': {'eventType': 'DIVIDEND',
    'dateEpochMs': 1787198400000,
    'amount': '0.91'}}],
 'postMarketTime': 1787097586,
 'regularMarketTime': 1787083201,
 'exchange': 'NMS',
 'messageBoardId': 'finmb_21835',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'gmtOffSetMilliseconds': -14400000,
 'market': 'us_market',
 'esgPopulated': False,
 'cryptoTradeable': False,
 'shortName': 'Microsoft Corporation',
 'longName': 'Microsoft Corporation',
 'regularMarketChangePercent': 0.266472,
 'regularMarketPrice': 481.63,
 'marketState': 'POSTPOST',
 'postMarketChangePercent': -0.056063686,
 'postMarketPrice': 481.36,
 'postMarketChange': -0.27001953,
 'regularMarketChange': 1.28,
 'fulldayPrice': 481.36,
 'regularMarketDayRange': '477.1505 - 484.27',
 'fullExchangeName': 'NasdaqGS',
 'fiftyTwoWeekLowChange': 132.43,
 'fiftyTwoWeekLowChangePercent': 0.37923822,
 'fiftyTwoWeekRange': '349.2 - 553.72',
 'fiftyTwoWeekHighChange': -72.089966,
 'fiftyTwoWeekHighChangePercent': -0.1301921,
 'fiftyTwoWeekChangePercent': -5.7712317,
 'dividendDate': 1788998400,
 'earningsTimestamp': 1785355200,
 'earningsTimestampStart': 1793217600,
 'earningsTimestampEnd': 1793217600,
 'earningsCallTimestampStart': 1785360600,
 'earningsCallTimestampEnd': 1785360600,
 'isEarningsDateEstimate': True,
 'epsTrailingTwelveMonths': 17.97,
 'epsForward': 23.57328,
 'epsCurrentYear': 19.7106,
 'priceEpsCurrentYear': 24.435076,
 'fiftyDayAverageChange': 67.80841,
 'fiftyDayAverageChangePercent': 0.16385904,
 'twoHundredDayAverageChange': 49.4581,
 'twoHundredDayAverageChangePercent': 0.1144408,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'averageAnalystRating': '1.4 - Strong Buy',
 'averageDailyVolume3Month': 40351725,
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 511108200000,
 'displayName': 'Microsoft',
 'trailingPegRatio': 1.56}

In [3]:
# 최근 5일간의 주가 정보 확인
hist = msft.history(period='5d')  
display(hist)

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2026-08-11 00:00:00-04:00,504.329987,505.329987,499.549988,503.809998,23049800,0.0,0.0
2026-08-12 00:00:00-04:00,499.989990,501.500000,491.519989,492.429993,29001500,0.0,0.0
2026-08-13 00:00:00-04:00,493.269989,501.339996,493.010010,496.880005,23039000,0.0,0.0
2026-08-14 00:00:00-04:00,496.359985,500.010010,493.920013,495.399994,16217600,0.0,0.0
2026-08-17 00:00:00-04:00,NaN,NaN,NaN,NaN,28250867,0.0,0.0

In [4]:
# 추천 정보 출력
# 해당 종목에 대한 애널리스트들의 분석 결과
msft.recommendations

# -1m : 한달전

  period  strongBuy  buy  hold  sell  strongSell
0     0m         14   39     3     0           0
1    -1m         14   40     3     0           0
2    -2m         13   41     3     0           0
3    -3m         12   41     3     0           0